seed: 42
models:
  separate: false
  policy:
    class: GaussianMixin
    clip_actions: true
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
    - name: image_features
      input: permute(STATES['rgb'], (0, 3, 1, 2))
      layers:
      - conv2d:
          out_channels: 32
          kernel_size: 8
          stride: 4
          padding: 0
      - conv2d:
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 0
      - conv2d:
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 0
      - conv2d:
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 0
      - flatten
      activations: elu
    - name: joint_features
      input: STATES['poses']
      layers:
      - 64
      - 64
      activations: elu
    - name: combined
      input: concatenate([image_features, joint_features])
      layers:
      - 512
      activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: false
    network:
    - name: image_features
      input: permute(STATES['rgb'], (0, 3, 1, 2))
      layers:
      - conv2d:
          out_channels: 64
          kernel_size: 8
          stride: 4
          padding: 0
      - conv2d:
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 0
      - conv2d:
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 0
      - conv2d:
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 0
      - flatten
      activations: elu
    - name: joint_features
      input: STATES['poses']
      layers:
      - 128
      - 128
      activations: elu
    - name: combined
      input: concatenate([image_features, joint_features])
      layers:
      - 256
      activations: elu
    output: ONE
memory:
  class: RandomMemory
  memory_size: -1
agent:
  class: PPO
  rollouts: 32
  learning_epochs: 5
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0003
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs:
    size: observation_space
    device: cuda:0
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs:
    size: 1
    device: cuda:0
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: false
  entropy_loss_scale: 0.01
  value_loss_scale: 2.0
  kl_threshold: 0.0
  rewards_shaper_scale: 2.0
  time_limit_bootstrap: false
  experiment:
    directory: "jetbot_project"
    experiment_name: ""
    write_interval: 100
    checkpoint_interval: 5000
    wandb: False
    wandb_kwargs:
      project: "IsaacLab_Implementation"
      name: "mybuddy_direct_reduced_fidelity"
trainer:
  class: SequentialTrainer
  timesteps: 400000
  environment_info: log
  close_environment_at_exit: false
