seed: 42
models:
  separate: false
  policy:
    class: GaussianMixin
    clip_actions: true
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [32, 32]
        activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: false
    network:
      - name: net
        input: STATES
        layers: [32, 32]
        activations: elu
    output: ONE
memory:
  class: RandomMemory
  memory_size: -1
agent:
  class: PPO
  rollouts: 32
  learning_epochs: 5
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0003
  # learning_rate_scheduler: KLAdaptiveLR
  # learning_rate_scheduler_kwargs:
  #   kl_threshold: 0.008
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs:
    size: observation_space
    device: cuda:0
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs:
    size: 1
    device: cuda:0
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: false
  entropy_loss_scale: 0.01
  value_loss_scale: 2.0
  kl_threshold: 0.0
  rewards_shaper_scale: 2.0
  time_limit_bootstrap: false
  experiment:
    directory: "jetbot_project"
    experiment_name: ""
    write_interval: 100
    checkpoint_interval: 5000
    wandb: False
    wandb_kwargs:
      project: "ME592"
      name: "jetbot_ppo"
trainer:
  class: SequentialTrainer
  timesteps: 400000
  environment_info: log
  close_environment_at_exit: false
